Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
   config.vm.network "private_network", ip: "192.168.56.38"
   config.vm.network "public_network"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
	   vb.cpus = "2"
   end

   config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc

      # Add the repository to Apt sources:
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
      sudo usermod -aG docker vagrant
   SHELL
end